version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: formulario_db
    environment:
      POSTGRES_DB: LocalBaseDatosJava
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  # API FastAPI
  api:
    build: .
    container_name: formulario_api
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=LocalBaseDatosJava
      - DB_USER=postgres
      - DB_PASSWORD=123456
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  # Nginx como proxy reverso (opcional)
  nginx:
    image: nginx:alpine
    container_name: formulario_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge